# Generated by Django 4.2.19 on 2025-03-05 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('safe_zone', models.TextField(blank=True, help_text='Optional: JSON defining safe zone coordinates')),
                ('update_interval', models.PositiveIntegerField(default=60, help_text='Update interval in seconds for tracking data')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Facebook Messenger'), ('instagram', 'Instagram'), ('snapchat', 'Snapchat')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='social_media/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(help_text='e.g., WhatsApp, Facebook, Instagram', max_length=50)),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('receiver', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, help_text='JSON data from sensors', null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.PositiveIntegerField(help_text='Total screen time in minutes')),
                ('app_breakdown', models.JSONField(help_text='JSON of app usage durations')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geolocation', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('microphone', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=False)),
                ('clipboard', models.BooleanField(default=False)),
                ('sensors', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('other', models.JSONField(blank=True, help_text='Additional permission statuses', null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='KeyloggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('keystrokes', models.TextField(help_text='Logged keystrokes')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keylogger_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(help_text='Radius in meters')),
                ('stealth_mode', models.BooleanField(default=False, help_text='Enable to hide app icon and run in background')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('platform', models.CharField(max_length=100)),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
                ('other_details', models.JSONField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('caller', models.CharField(max_length=100)),
                ('callee', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='tracking.child')),
            ],
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('foreground_duration', models.PositiveIntegerField(help_text='Time in seconds')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage_logs', to='tracking.child')),
            ],
        ),
    ]
